name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정에 자동 실행
  workflow_dispatch: # 수동으로 버튼 눌러서 실행 가능하게 설정

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
